In [ ]:


# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [14]:
# 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np


In [68]:
# 2. Create a null vector of size 10 (★☆☆)
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [21]:
# 4. Create a vector with values ranging from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [35]:
# 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
b=np.arange(0,9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
# 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
non=[1,2,0,0,4,0]
np.nonzero(non)

(array([0, 1, 4]),)

In [45]:
# 7. Create a 3x3 identity matrix (★☆☆)
a= np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
# 8. Create a 3x3x3 array with random values (★☆☆)
a = np.random.random((3,3,3))
print(a)

[[[0.68218442 0.20608054 0.42607772]
  [0.21148526 0.07623966 0.98082548]
  [0.80583609 0.34902082 0.90562595]]

 [[0.81188097 0.70240161 0.69881773]
  [0.12781562 0.59867493 0.60496614]
  [0.50600236 0.47983209 0.14717411]]

 [[0.58376692 0.49015267 0.40785349]
  [0.18555383 0.07849641 0.20991423]
  [0.78073521 0.90143769 0.22352352]]]


In [66]:
# 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

a = np.random.random((10,10))
print(a)
np.min(a)


[[0.78924046 0.84462912 0.88270963 0.4267392  0.8993446  0.57878244
  0.89629421 0.3978671  0.66720997 0.29191749]
 [0.35687526 0.4212169  0.11450617 0.94686989 0.89782283 0.40889378
  0.86710949 0.78038949 0.38075732 0.73420318]
 [0.33981969 0.26943805 0.09862289 0.82138468 0.60653758 0.75546343
  0.99010701 0.79099079 0.45892337 0.50749   ]
 [0.60462295 0.1540069  0.97895956 0.28015676 0.9751937  0.49096696
  0.26187665 0.05916668 0.26941878 0.88657098]
 [0.0410613  0.62236023 0.98724398 0.73314401 0.51512877 0.06710206
  0.47064958 0.24486451 0.5636143  0.47194498]
 [0.46739008 0.81387195 0.28373278 0.24353789 0.69996012 0.32216129
  0.21545062 0.31760596 0.94283187 0.50111179]
 [0.39395224 0.92582496 0.0681454  0.33917734 0.30336332 0.59356382
  0.95403594 0.77772202 0.93483028 0.47048673]
 [0.86622543 0.55322266 0.53383907 0.22449002 0.86859987 0.92737266
  0.71467931 0.41277439 0.65184648 0.94203393]
 [0.61186889 0.85885152 0.19588158 0.51624911 0.66141612 0.87452699
  0.21600269

0.011534807933695546

In [67]:
#inimum and maximum values 
np.max(a)

0.9901070051396262

In [78]:
# 10. Create a random vector of size 30 and find the mean value (★☆☆)
a = np.random.random(30)
a

array([0.95581564, 0.46275769, 0.09429016, 0.45984687, 0.61567093,
       0.87273046, 0.03294104, 0.29658733, 0.89626195, 0.8665892 ,
       0.61606208, 0.58167994, 0.03563714, 0.15867082, 0.33034247,
       0.01415451, 0.31552962, 0.68363684, 0.47292083, 0.69820467,
       0.05614423, 0.21601106, 0.70170057, 0.70229899, 0.67304956,
       0.07709044, 0.46813566, 0.51347076, 0.59622686, 0.7293185 ])

In [79]:
#find the mean value 
np.mean(a)

0.47312589384307024

In [152]:
# 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [95]:
# 12. Normalize a 5x5 random matrix (★☆☆)
a=np.random.random((5,5))
a

array([[0.5033588 , 0.34223132, 0.37277208, 0.13065458, 0.03547912],
       [0.61494171, 0.18578073, 0.45662028, 0.17784572, 0.69484932],
       [0.03128019, 0.54190109, 0.70652017, 0.70589343, 0.91482206],
       [0.96854306, 0.2801239 , 0.36151512, 0.22395102, 0.52890256],
       [0.30478312, 0.65525826, 0.63982814, 0.47782394, 0.73393605]])

In [98]:
#Normalized
a=(a -np.mean(a))/np.std(a)
a

array([[ 0.15744955, -0.48038775, -0.35948946, -1.31793285, -1.69469324],
       [ 0.59916028, -1.09971112, -0.027569  , -1.13112258,  0.91548157],
       [-1.71131508,  0.31002259,  0.96168166,  0.95920066,  1.78626297],
       [ 1.99892228, -0.72624541, -0.40405112, -0.94861069,  0.25856677],
       [-0.62862973,  0.75875691,  0.69767541,  0.05636754,  1.07020985]])

In [99]:
# 13. How to find common values between two arrays? (★☆☆)
a=np.arange(0,3)
b=np.arange(1,4)
a,b

(array([0, 1, 2]), array([1, 2, 3]))

In [100]:
np.intersect1d(a,b)


array([1, 2])

In [104]:
# 14. Create a random vector of size 10 and sort it (★★☆)
a=np.random.random(10)
a

array([0.00282626, 0.13786616, 0.65195365, 0.30984929, 0.03129226,
       0.23841463, 0.13805066, 0.70779735, 0.83991599, 0.10158354])

In [106]:
a=np.sort(a)
a

array([0.00282626, 0.03129226, 0.10158354, 0.13786616, 0.13805066,
       0.23841463, 0.30984929, 0.65195365, 0.70779735, 0.83991599])

In [118]:
# 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
a=np.random.random(10)
a

array([0.52695319, 0.23712924, 0.16082478, 0.67735538, 0.75963762,
       0.7814827 , 0.62049332, 0.85878521, 0.21075244, 0.29511775])

In [126]:
b=np.argmax(a)
b

5

In [128]:
a[5]=0
a

array([0.52695319, 0.23712924, 0.16082478, 0.67735538, 0.75963762,
       0.        , 0.62049332, 0.        , 0.21075244, 0.29511775])

In [137]:
# 16. Subtract the mean of each row of a matrix (★★☆)
a=np.random.random((3,3))
a


array([[0.85112039, 0.56908138, 0.86836679],
       [0.15008047, 0.89682124, 0.1623108 ],
       [0.46890831, 0.57060164, 0.80554101]])

In [160]:
b=np.mean(a, axis=1, keepdims=True)
print(b)

[[0.2]
 [0.4]
 [0.6]
 [0.8]
 [1. ]]


In [162]:
c=a-b
c

array([[ 0.8, -0.2, -0.2, -0.2, -0.2],
       [-0.4,  1.6, -0.4, -0.4, -0.4],
       [-0.6, -0.6,  2.4, -0.6, -0.6],
       [-0.8, -0.8, -0.8,  3.2, -0.8],
       [-1. , -1. , -1. , -1. ,  4. ]])

In [163]:
# 17. How to get the n largest values of an array (★★★)
a=np.arange(10)
n=5
b=np.argsort(a)
b

array([5, 9, 8, 2, 0, 6, 3, 7, 4, 1])

In [147]:
# 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
a=np.random.random((5,3))
a

array([[0.46810644, 0.74427102, 0.00895867],
       [0.72575535, 0.12876493, 0.76186781],
       [0.75032816, 0.53078148, 0.96986276],
       [0.12764613, 0.20186851, 0.07349369],
       [0.43339585, 0.10311588, 0.48976416]])

In [ ]:
a=np.where

In [ ]:
`hint: np.where`